services:
 mongodb:
    image: mongo:latest 
    container_name: mongodb_container
    ports:
      - "27017:27017" 
 xuxu_jwt:
    build: "."
    volumes:
      - ".:/usr/xuxu"
      - "/usr/xuxu/node_modules"
    ports:
      - "8000:3000"
    env_file:
      - ".env"
    depends_on:
      - mongodb
    command: npm start
    

